### date:2021年11月29日
### author: www.mrdoc.fun | jonnyan404
### 转载请保留来源
version: '3.3'
services:
    ztncui:
        container_name: ztncui
	restart: always
        environment:
            # - MYADDR=公网地址(不填自动获取)
            - HTTP_PORT=4000
	    - HTTP_ALL_INTERFACES=yes
	    - ZTNCUI_PASSWD=mrdoc.fun
        ports:
            - '4000:4000'
	    # - '3180:3180'具体参考GitHub项目说明
        image: keynetworks/ztncui
